# -*- mode: ruby -*-
# vi: set ft=ruby :

load "../settings.sh"
NETWORK = LAN_IP.split(/\.([^.]*)$/)[0]
IP = NETWORK + ".1"

Vagrant.configure("2") do |config|
  
  config.vm.box = "ubuntu/bionic64"
  
  config.vm.network "public_network", ip: IP, netmask: "255.255.255.0", bridge: LAN_IF
  
  config.vm.provider "virtualbox" do |virtualbox|
	  # Enable promiscuous mode
  	  virtualbox.customize ["modifyvm", :id, "--nicpromisc2", "allow-all"]
	  # Setting RAM
	  virtualbox.memory = "512"

  end
  config.vm.synced_folder "../", "/vagrant"
  config.vm.provision "shell", path: "install.sh"

end
