# -*- mode: ruby -*-
# vi: set ft=ruby :

load "../settings.sh"
INTERFACE = %x(  ip route | grep default | cut -d' ' -f5 )
DHCP_ADDRESS = NETWORK+".234"

Vagrant.configure("2") do |config|
  
  config.vm.box = "ubuntu/bionic64"
  
  config.vm.network "public_network", ip: DHCP_ADDRESS, netmask: "255.255.255.0", bridge: INTERFACE.strip
  
  config.vm.provider "virtualbox" do |virtualbox|
	  # Enable promiscuous mode
  	  virtualbox.customize ["modifyvm", :id, "--nicpromisc2", "allow-all"]
	  # Setting RAM
	  virtualbox.memory = "512"

  end
  config.vm.synced_folder "../", "/vagrant"
  config.vm.provision "shell", path: "install.sh"

end
